### ISSUE TITLE
Would love to help make this look more like Messages inputAccessoryView...

### ISSUE THREAD

**Issue by kylebshr** [AlexLittlejohn/ALTextInputBar#10]
...but I'm not too sure how to start. I forked the project, but I'm not too sure where you're using autolayout and where not. Which class do I need to add the UITextField background and separator line to the top of? Would love some pointers.

**Comment by AlexLittlejohn** [comment]
There is now an option to toggle on a border view for the text view. Options have also been added to control color, width and corner radius etc.
