### ISSUE TITLE
Multi-line is fairly buggy

### ISSUE THREAD

**Issue by kylebshr** [AlexLittlejohn/ALTextInputBar#11]
Here is a video showing that the top line often disappears with multiple lines — is this something you're able to reproduce, or perhaps an issue I've introduced through my customizations? Here's how I'm setting up the bar:

    sendButton.titleLabel?.font = UIFont(name: "AvenirNext-Medium", size: 17)
    sendButton.setTitleColor(UIColor.murmurColor(), forState: .Normal)
    sendButton.setTitleColor(UIColor.murmurColor().colorWithAlphaComponent(0.3), forState: .Highlighted)
    sendButton.setTitle("Send", forState: .Normal)
    sendButton.sizeToFit()
    sendButton.addTarget(self, action: "didPressRightButton:", forControlEvents: .TouchUpInside)

    textInputBar.backgroundColor = UIColor.whiteColor()
    textInputBar.alwaysShowRightButton = false
    textInputBar.horizontalPadding = 8
    textInputBar.horizontalSpacing = 8
    textInputBar.rightView = sendButton
    textInputBar.defaultHeight = 45

    textInputBar.textView.placeholder = "Comment"
    textInputBar.textView.font = UIFont(name: "AvenirNext-Medium", size: 15)
    textInputBar.textView.tintColor = UIColor.murmurColor()
    textInputBar.textView.placeholderColor = UIColor.grayColor()

And here's a link to the video: https://vid.me/nT4d

Edit: this appears to be an iOS 9 issue, and it works as expected on iOS 8

**Comment by vikmeup** [comment]
@AlexLittlejohn same thing happen to me. Would you able to fix it? Thanks.
