### ISSUE TITLE
How to add an input bar in an UITableview with Tabbar?

### ISSUE THREAD

**Issue by DesmondPang** [AlexLittlejohn/ALTextInputBar#12]
How to add an input bar above the tabor like the Facebook/Instagram app in comment view.

**Comment by AlexLittlejohn** [comment]
You could achieve this by not specifying the input bar as an inputAccessoryView in your viewController.
Rather add it as a subview and the use the keyboard frame change notifications to position it as necessary.

The example project shows this method.

**Comment by DesmondPang** [comment]
From your example, the input bar view is added into view but now I use UITableViewController
 I have already tried 
self.view.window?.addSubview(textInputBar), 
self.tabBarController!.view.addSubview(textInputBar),
self.parentViewController?.view.addSubview(textInputBar),
self.tableview.addSubview(textInputBar),
but no one works.

Do I need to use UIViewController extending UITableViewDataSource and UITableViewDelegate rather than use UITableViewController directly?

**Comment by AlexLittlejohn** [comment]
Use a regular viewController instance as in the example for best results.
