### ISSUE TITLE
Hi thank you for ALTextInputBar

### ISSUE THREAD

**Issue by wistala** [AlexLittlejohn/ALTextInputBar#15]
How can i reset and clean textview after sending a successfully request ?

**Comment by AlexLittlejohn** [comment]
To empty the text view just set its text to an empty string
```
inputBar.textView.text = ""

**Comment by wistala** [comment]
yes i did it but i want to hide Send button like when the ALTextInputBar init after i send my message

**Comment by canaksoy** [comment]
how can I reset after writing a multiline text in textView to one line? after inputBar.textView.text = ""
