### ISSUE TITLE
TextInputBar dismiss when touch places in bar other than textView

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [AlexLittlejohn/ALTextInputBar#16]
add codes below to ALTextInputBar should prevent this from happening. 
```Swift
   override public func touchesBegan(touches: Set<UITouch>, withEvent event: UIEvent?) {
        return
    }
    override public func touchesEnded(touches: Set<UITouch>, withEvent event: UIEvent?) {
        return
    }
    override public func touchesMoved(touches: Set<UITouch>, withEvent event: UIEvent?) {
        return   
    }
```

**Comment by AlexLittlejohn** [comment]
The bar has a dismiss on drag which is meant to be a feature. 
If this is your issue then you need to set your scroll view to not have an interactive dismiss

````swift
scrollView.keyboardDismissMode = UIScrollViewKeyboardDismissMode.Interactive

// becomes

scrollView.keyboardDismissMode = UIScrollViewKeyboardDismissMode.None

````

Other than that I can't reproduce a scenario similar to what you're describing where this code would be necessary.

**Comment by Nick-The-Uncharted** [comment]
I started another project and used this library again (This is really convenient).
But I encounter this problem again.
Actually I mean when I touched the background of surrounding area of textView , the textView resigned as first responder and my tableView didn't become the next first responder because the touch didn't happen in my tableView.
