### ISSUE TITLE
TableView

### ISSUE THREAD

**Issue by justin-nodeboy** [AlexLittlejohn/ALTextInputBar#18]
Hey there

I would like to use your lib for usage where I have a tableview (which is inside a tab group).

I have added the code following your example but I can't see the input bar anywhere on the screen.

Is there anything special I need to be doing?

Thanks

Justin

**Comment by AlexLittlejohn** [comment]
Which example are you following? The one in the project directory (preferred) or the one in the readme. They are the 2 different approaches to handling the input bar. 

Also note that putting it inside a viewController which already has a tab bar is not going to be the best experience.

**Comment by justin-nodeboy** [comment]
Yeah I get you, just been looking at a couple of messaging apps and they don't have the toolbar. Which is fine, I'll just change around my UI a bit. At the moment this particular view is a child of a view in nav controller inside a tab group.

Let me try it in a view outside of the tab group and see if it sorts it.

But you don't for-see there should be any issues with it sharing the view with a table?

**Comment by justin-nodeboy** [comment]
Ok, just for now I have stuck it in a Modal, I see the Textfield pinned to the bottom, but it's not connected to the Keyboard, so when the keyboard shows it covers it up. Also, I am setting the view up like so:

    func configureInputBar() {
        let rightButton = UIButton(frame: CGRectMake(0, 0, 44, 44))
        
        rightButton.setTitle("Post", forState: .Normal)
        
        keyboardObserver.userInteractionEnabled = false
        
        textInputBar.showTextViewBorder = true
        textInputBar.rightView = rightButton
        textInputBar.frame = CGRectMake(0, view.frame.size.height - textInputBar.defaultHeight, view.frame.size.width, textInputBar.defaultHeight)
        textInputBar.backgroundColor = UIColor(white: 0.95, alpha: 1)
        textInputBar.keyboardObserver = keyboardObserver
        
        view.addSubview(textInputBar)
    }

But I don't see the right hand button?

**Comment by AlexLittlejohn** [comment]
You will need to add listeners to handle the keyboard notifications i.e. frameChange, show and hide. See example viewcontroller for more details

**Comment by justin-nodeboy** [comment]
Wow, I missed that, so added them in and the field vanishes.

Here they are:
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "keyboardFrameChanged:", name: ALKeyboardFrameDidChangeNotification, object: nil)
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "keyboardWillShow:", name: UIKeyboardWillShowNotification, object: nil)
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "keyboardWillHide:", name: UIKeyboardWillHideNotification, object: nil)

Without them the field is visible.

**Comment by AlexLittlejohn** [comment]
Have you added the keyboard observer?
Have a look at the [example](https://github.com/AlexLittlejohn/ALTextInputBar/blob/master/Example/ViewController.swift) to see how to use that.

**Comment by justin-nodeboy** [comment]
Yep have now checked everything to the examples. Looking at the ViewController in the example project. :(

**Comment by AlexLittlejohn** [comment]
Then i'm not sure what else could be going wrong and i've no idea how to help you further, short of looking at the rest of your implementation.

**Comment by justin-nodeboy** [comment]
It's been about a week of trying various things just to get something like this to work, not blaming your library, I'm just annoyed something as common as this is, is such a pain in the ass in iOS.

Anyway, thanks for your help so far. I'll have a play around with it and see if I can get the thing working.
