### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Oniiichan** [AlexLittlejohn/ALTextInputBar#2]
First of all, great work and thanks for this useful project.

Getting compile error

![screen shot 2015-05-07 at 4 34 13 am](https://cloud.githubusercontent.com/assets/10688420/7511386/81c4ed6a-f472-11e4-9ece-1ebc19c35d8f.png)

**Comment by Oniiichan** [comment]
I think they as! should be as?

**Comment by Oniiichan** [comment]
Another issue:

![screen shot 2015-05-07 at 4 39 34 am](https://cloud.githubusercontent.com/assets/10688420/7511486/1d20c6bc-f473-11e4-8137-e82581637090.png)

**Comment by AlexLittlejohn** [comment]
Are you running Xcode 6.3 and swift 1.2?

**Comment by Oniiichan** [comment]
Version 6.1.1. Ill upgrade now.

**Comment by AlexLittlejohn** [comment]
Cool beans, I'll add a note to the readme with those requirements
