### ISSUE TITLE
Example App too confusing

### ISSUE THREAD

**Issue by lfarah** [AlexLittlejohn/ALTextInputBar#20]
I think that the example app is really well-made, but it is too confusing.
We should have the example show the ALTextInputBar just like the ```Readme.md``` does, but also have the a send button that prints the ```textInputBar.text```.
I don't know about you, but I use library example apps for two things:

1. Quickly test the library
2. Copy and paste the methods to quickly implement the library in my code

What are your thoughts?

**Comment by AlexLittlejohn** [comment]
While the Readme implementation is much simpler, the example implementation is far more robust under 99% of use cases. 
As a side note, you will also find that most messaging apps use the example method of attaching the bar to the keyboard.

**Comment by AlexLittlejohn** [comment]
However I agree that there is room for improvement in the implementation and possibly finding ways to simplify it.
