### ISSUE TITLE
Setting delegate for ALTextView

### ISSUE THREAD

**Issue by Nathan961207** [AlexLittlejohn/ALTextInputBar#21]
`class tableViewForPartyChatAndInformationViewController: UIViewController, UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate,  ALTextInputBarDelegate, ALTextViewDelegate ` 

ALTextViewDelegate should help using the functions such as "textViewDidChange" however it gives me an error saying this class can not conform to protocol ALTextViewDelegate. Any idea on how to set delegates in my class? I am trying to make the the InputBar first responder but it does not work, i got it to work when i used the default UITextView but i had issues with resizing the input toolbar

**Comment by AlexLittlejohn** [comment]
You do not need to conform to `ALTextInputBarDelegate` and `ALTextViewDelegate`. Everything from the TextView is passed through to the `ALTextInputBarDelegate`.

**Comment by Nathan961207** [comment]
Well the textView does not listen to the delegate methods or resign to firstresponder

Date: Tue, 26 Apr 2016 01:24:55 -0700

**Comment by AlexLittlejohn** [comment]
Can you give an example of how you are setting the delegates and using the lib?

**Comment by Nathan961207** [comment]
I am using a UIView to hold the textView at the bottom of the screen(created it in storyboard so i can use autoLayout), when i press on the textView to type the inputaccessoryView is your ALTextInputBar. I followed the example project but i didn´t really understand on how you managed to get ALTextInputBar at the bottom on the screen. Did you create it programmatically and then set itself as inputaccessoryView or are you using two different "InputBar".
I could use the delegate 'textViewDidBeginEditing(textView: ALTextView)' but since i cannot set delegate like 'myTextView.delegate = self' because i cannot implement the protocol 'ALTextViewDelegate' in the class the function'textViewDidBeginEditing(textView: ALTextView)' is never called.
Could you maybe inform me on how to properly set up the first "InputBar" you see when the View is loaded. 
Date: Tue, 26 Apr 2016 02:06:04 -0700

**Comment by AlexLittlejohn** [comment]
hmm, have a look at the readme example instead. It shows a much simpler set up using only 1 textInputBar.

**Comment by AlexLittlejohn** [comment]
Everything needs to be set up programatically

**Comment by Nathan961207** [comment]
I went trough your readme and i tried to mimic your project without any success , i managed to add the ALTextInputBar to the view programmatically but when calling the function "keyBoardWillShow" the keyboard does not move up. So i am gonna make it an InputAccessoryView of a textField instead. How would i use the ALTextView delegates in my class? 

Date: Tue, 26 Apr 2016 02:32:02 -0700

**Comment by AlexLittlejohn** [comment]
If you've set it up correctly in your view controller as your view controllers' `inputAccessoryView` then they only thing required to show the keyboard will be the user tapping the text view.

**Comment by AlexLittlejohn** [comment]
If you can please share some code so i can tell you exactly where you may be going wrong.

**Comment by Nathan961207** [comment]
Some info before you should read the code: I left space at the bottom and created an UIView there called "contstraitsForTextINputBar".  When i press on the textView the keyBoard appears but the textInputBar does not move up. Also the textInputBar does not show when i use "override var inputAccessoryView: UIView?". 
This works excellent when i use it as an inputAccessoryView but since i cannot use delegates and the button does not seem to work when i call the action for it i can never dismiss the keyboard.

let textInputBar = ALTextInputBar()








let keyboardObserver = ALKeyboardObservingView()







@IBOutlet weak var contstraitsForTextINputBar: UIView!


override func viewDidLoad(animated:Bool) {        super.viewDidLoad(true)NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(ViewController.keyboardFrameChanged(_:)), name: ALKeyboardFrameDidChangeNotification, object: nil)        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(ViewController.keyboardWillShow(_:)), name: UIKeyboardWillShowNotification, object: nil)









        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(ViewController.keyboardWillHide(_:)), name: UIKeyboardWillHideNotification, object: nil)}
override func viewWillAppear(animated: Bool) {        super.viewWillAppear(true)                // let leftButton = UIButton(frame: CGRectMake(0, 0, 44, 44))        let rightButton = UIButton(frame: CGRectMake(0, 0, 44, 44))                //leftButton.setImage(UIImage(named: "leftIcon"), forState: UIControlState.Normal)        rightButton.frame = CGRectMake(0, 0, 44, 39)  // <-- add frame (or use sendButton.sizeToFit() once the titleLabel has been added)        rightButton.enabled = false        rightButton.titleLabel?.font = UIFont(name: "HelveticaNeue-Light", size: CGFloat(14))        rightButton.setTitle("Send", forState: .Normal)        rightButton.setTitleColor(UIColor.blackColor(), forState: .Disabled)        rightButton.setTitleColor(UIColor.blackColor(), forState: .Normal)        rightButton.addTarget(self, action: #selector(tableViewForPartyChatAndInformationViewController.dismissKeyBoard), forControlEvents: .AllEvents)                keyboardObserver.userInteractionEnabled = false                textInputBar.showTextViewBorder = false        //textInputBar.leftView = leftButton        textInputBar.rightView = rightButton        textInputBar.frame = CGRectMake(0,contstraitsForTextINputBar.frame.origin.y, view.frame.size.width, contstraitsForTextINputBar.frame.size.height)        textInputBar.backgroundColor = UIColor(white: 1, alpha: 1)        let topBorderReal: UIView = UIView()        topBorderReal.backgroundColor = UIColor(patternImage: UIImage(named: "Path 4")!)        topBorderReal.frame = CGRectMake(0, 0, textInputBar.frame.size.width, 1)                textInputBar.addSubview(topBorderReal)        let rightBorderReal: UIView = UIView()        rightBorderReal.backgroundColor = UIColor(patternImage: UIImage(named: "Path 4")!)        rightBorderReal.frame = CGRectMake(textInputBar.textView.frame.size.width - 1, 0, 1, textInputBar.textView.frame.size.width)        textInputBar.textView.addSubview(rightBorderReal)        textInputBar.keyboardObserver = keyboardObserver        








































        textInputBar.textView.textColor = UIColor.blackColor()
        view.addSubView(textInputBar)



 // This is also required    override func canBecomeFirstResponder() -> Bool {        return true










    }
override var inputAccessoryView: UIView? {        get {            return keyboardObserver        }    }
func keyboardFrameChanged(notification: NSNotification) {        if let userInfo = notification.userInfo {            let frame = (userInfo[UIKeyboardFrameEndUserInfoKey] as! NSValue).CGRectValue()            textInputBar.frame.origin.y = frame.origin.y        }    }        func keyboardWillShow(notification: NSNotification) {        if let userInfo = notification.userInfo {            let frame = (userInfo[UIKeyboardFrameEndUserInfoKey] as! NSValue).CGRectValue()            textInputBar.frame.origin.y = frame.origin.y        }    }        func keyboardWillHide(notification: NSNotification) {        if let userInfo = notification.userInfo {            let frame = (userInfo[UIKeyboardFrameEndUserInfoKey] as! NSValue).CGRectValue()            textInputBar.frame.origin.y = frame.origin.y        }


























    }func dismissKeyBoard(){        textInputBar.backgroundColor = UIColor.blueColor()









    }Date: Fri, 29 Apr 2016 09:04:26 -0700

**Comment by Nathan961207** [comment]
the button works, i forgot i set it like this in the code 








rightButton.enabled = false

Date: Fri, 29 Apr 2016 09:04:26 -0700

**Comment by AlexLittlejohn** [comment]
ok so the first issue I see is that you aren't adjusting your constraint when the keyboard appears/moves/hides.

However i would recommend using it like this instead:

```swift
let textInputBar = ALTextInputBar()

override func viewDidLoad() {
  super.viewDidLoad()
  NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(keyboardWillShow(_:)), name: UIKeyboardWillShowNotification, object: nil)
  NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(keyboardWillHide(_:)), name: UIKeyboardWillHideNotification, object: nil)
}

override func viewWillAppear(animated: Bool) {
  super.viewWillAppear(animated: true)
  rightButton.frame = CGRectMake(0, 0, 44, 39)
  rightButton.enabled = false
  rightButton.titleLabel?.font = UIFont(name: "HelveticaNeue-Light", size: CGFloat(14))
  rightButton.setTitle("Send", forState: .Normal)
  rightButton.setTitleColor(UIColor.blackColor(), forState: .Disabled)
  rightButton.setTitleColor(UIColor.blackColor(), forState: .Normal)
  rightButton.addTarget(self, action: #selector(dismissKeyBoard), forControlEvents: .AllEvents)
  textInputBar.showTextViewBorder = false
  textInputBar.rightView = rightButton
  textInputBar.textView.textColor = UIColor.blackColor()
}

override func canBecomeFirstResponder() -> Bool {
  return true
}

override var inputAccessoryView: UIView? {
  return textInputBar
}

func keyboardWillShow(notification: NSNotification) {

}

func keyboardWillHide(notification: NSNotification) {

}

func dismissKeyBoard(){
  textInputBar.textView.resignFirstResponder()
}

```

**Comment by Nathan961207** [comment]
Where should i set the constraints? I used the same code as you did in your example

Date: Fri, 29 Apr 2016 09:55:49 -0700

**Comment by AlexLittlejohn** [comment]
You don't need constraints

**Comment by Nathan961207** [comment]
It seems to automatically become firstresponder by clicking on the textView also i do not need to it as subview anymore
calling resignFirstResponder does not work because i have not set delegate.Calling self.view.endEditing(true) does close the keyboard. Thanks :)

Date: Fri, 29 Apr 2016 10:08:09 -0700
