### ISSUE TITLE
Setting tint color does not have effect. 

### ISSUE THREAD

**Issue by lekanadeyeri** [AlexLittlejohn/ALTextInputBar#27]
textInputBar.backgroundColor = UIColor().HexToColor("#FFFFFF") --> Creates white background
textInputBar.tintColor = UIColor().HexToColor("#F87E51") ---> Stays grey, when I set it to orange

Nice pod, really enjoy using it.

**Comment by AlexLittlejohn** [comment]
Nothing has been implemented to listen for tintColor changes. You can change the color of individual elements separately using the properties provided on the inputBar.

**Comment by lekanadeyeri** [comment]
textInputBar.textView.tintColor = UIColor().HexToColor("#F87E51")
