### ISSUE TITLE
Xcode 8 and Swift 3 support

### ISSUE THREAD

**Issue by elprl** [AlexLittlejohn/ALTextInputBar#29]
Any plans for Swift 3 support? Cocoapods install on xcode 8 errors.
Recommend creating a branch for Swift-2.3.

**Comment by AlexLittlejohn** [comment]
It's in progress on the develop branch. Just a few breaking bugs to iron out first.

**Comment by shjnbe** [comment]
Can someone tell me when will supported version come?

**Comment by AlexLittlejohn** [comment]
This is already available, ill update the realm to reflect. Please make sure you are using the latest Cocoapods beta version to install.
