### ISSUE TITLE
issue in tut

### ISSUE THREAD

**Issue by davidseek** [AlexLittlejohn/ALTextInputBar#30]
isn't there a mistake in the description?

you say:

`override func canBecomeFirstResponder() -> Bool {
        return true
    }`

but shouldnt it be var instead of func?

**Comment by AlexLittlejohn** [comment]
That is correct, it is a relic from the swift 2.0 days. I'll update the
readme shortly

**Comment by davidseek** [comment]
I have another problem. just posting it in here. to save room.
if i'm having your input view within a view controller that is presented modally (transition from bottom to top), the input view is missing completely. if i'm using a custom transition from right to left (like in a navigationbarcontroller), the input view is present (same setup!), but one i hit the input view and the keyboard pops up, the input view is hidden. if i hit any button on the keyboard, the input view jumps up.
any idea? i can provide a test git project, if you have no idea what i'm talking about.

**Comment by davidseek** [comment]
https://github.com/davidseek/ALTextInputBarIssue
