### ISSUE TITLE
Issue on ensureCaretDisplaysCorrectly()

### ISSUE THREAD

**Issue by rogomantik** [AlexLittlejohn/ALTextInputBar#31]
Using v1.1.0
simulator iphone 6s ios 9.3

Log show
requesting caretRectForPosition: while the NSTextStorage has oustanding changes {2, 1}
requesting caretRectForPosition: while the NSTextStorage has oustanding changes {3, 1}
on enter tap (new line)

possible fix:
```
        dispatch_async(dispatch_get_main_queue()) { 
            self.ensureCaretDisplaysCorrectly()
        }
```

**Comment by AlexLittlejohn** [comment]
Fixed #40
