### ISSUE TITLE
Wrong line height

### ISSUE THREAD

**Issue by NausJessy** [AlexLittlejohn/ALTextInputBar#33]
When getting to the end of the line, the text view's height isn't updated directly but only when continuing typing. In the screenshot, I began typing the word "new" but it doesn't show up. 
![img_2272](https://cloud.githubusercontent.com/assets/14758083/21050162/62c040d2-be19-11e6-9cc8-cd6af7c75a10.PNG)
I have to type some more text before the text view's height is correct.
![img_2273](https://cloud.githubusercontent.com/assets/14758083/21050218/bc62c420-be19-11e6-9479-86fb787de01b.PNG)

**Comment by canaksoy** [comment]
height problem continues on first init of the view in 1.1.5
