### ISSUE TITLE
Crash on UIDevice.floatVersion

### ISSUE THREAD

**Issue by ThomasCassany** [AlexLittlejohn/ALTextInputBar#34]
Hi,

On every device with an iOS version X.Y.Z (ex: 10.1.1), `UIDevice.floatVersion` crash.  I had a look where you used it, it's only to check if the device has a version less than 8.0. You can use that method instead: 
```
internal static func isVersionLessThan(_ version: String) -> Bool {
    return UIDevice.current.systemVersion > version
}
```

I'll try to create a pull request today.

**Comment by AlexLittlejohn** [comment]
I think it may just be simpler to remove the version check altogether and drop iOS 7 support
