### ISSUE TITLE
ALTextInputBar dismissing keyboard issues

### ISSUE THREAD

**Issue by JamesPSScott** [AlexLittlejohn/ALTextInputBar#38]
Hi, first of all:  Awesome control!  This should save me a ton of time if I can get it figured out.  Here's my issue.  I have a Facebook-like single post + comments view where a user can add more comments with the ALTextInputBar accessory.

When I click in ALTextInputBar it brings up my keyboard appropriately, however when I want to dismiss the keyboard I cannot.  I found a hacky way to do it by calling resignFirstResponder and becomeFirstResponder, but that fires keyboard shown notifications again which mess up my sizing code.  (In my keyboard shown notification I adjust the constraint for the size of the UITableView so the user can scroll and see the whole thing while they are editing)

What is the appropriate way to dismiss the keyboard when the screen is touched with this control?

**Comment by DazChong** [comment]
Did you assigned `.interactive`/`.onDrag` for your `tableView`/`collectionView`/`scrollView`?

**Comment by JamesPSScott** [comment]
To be honest, I never even heard of this technique before!  I'll check this out.  Thanks for the idea!
