### ISSUE TITLE
Dismiss Keyboard

### ISSUE THREAD

**Issue by Oniiichan** [AlexLittlejohn/ALTextInputBar#4]
Thank you for this. How can you dismiss the keyboard on tap outside or when hitting "return".

**Comment by AlexLittlejohn** [comment]
Dismissing the keyboard on tap is relatively simple. Just add a gesture recogniser to your view and then call resignFirstResponder() when you want to dismiss the keyboard.

**Comment by AlexLittlejohn** [comment]
v1.0.5 adds a delegate to the input bar which will allow you to access most of the textview delegate methods as well as knowing when the return key is pressed.

**Comment by Oniiichan** [comment]
Hi Alex. Thanks for the response. I was able to dismiss the keyboard using:

    textInputBar.textView.resignFirstResponder()

However, the textInputBar covers the view when the keyboard pops up. Is there a way to shift the view up when the keyboard is present?

Thanks again for your help!

**Comment by Oniiichan** [comment]
Thank Alex, I was able to resign the first responder. However, would you mind specifying which delegate to use to change the return button to a "send" button instead of adding a new line?
