### ISSUE TITLE
Right Button Pressed

### ISSUE THREAD

**Issue by Oniiichan** [AlexLittlejohn/ALTextInputBar#5]
Would you mind specifying which delegate to use to change the return button to a "send" button that has an action instead of adding a new line.  The following does not get called when pressing return:

    func textViewShouldReturn(textView: ALTextView) -> Bool {
            println("000")
            self.view.endEditing(true);
            textInputBar.textView.resignFirstResponder()
            return false
    }

Also, what is the function to use to specify what to do when the user presses the right button?

**Comment by AlexLittlejohn** [comment]
Are you specifying a delegate object for the input bar?

The right and left views are your responsibility, you would usually specify your own button instance to a left or right view and you can add you own target to it as you would on any button.

**Comment by Oniiichan** [comment]
Alex, 

Would you mind showing an example on how to specify a button instance on the right view and give it an action?

Thank you

**Comment by AlexLittlejohn** [comment]
This line
`textInputBar.rightView!.addSubview(button)`

should be:
`textInputBar.rightView = button`

**Comment by Oniiichan** [comment]
I made the changes you suggested and now the rightView looks mispositioned on top of leftView.
![screen shot 2015-05-20 at 8 11 37 pm](https://cloud.githubusercontent.com/assets/10688420/7739300/a05cdbe2-ff2c-11e4-81d7-52b77d9ee688.png)

Code:

    func createRightButton() {
        var rightButton = UIButton(frame: CGRectMake(0,0,44,44))
        rightButton.addTarget(self, action: "rightButtonTapAction:", forControlEvents: UIControlEvents.TouchUpInside)
        textInputBar.rightView = rightButton

    }
