### ISSUE TITLE
ALTextInputBar Disappears when Poping ViewController

### ISSUE THREAD

**Issue by Oniiichan** [AlexLittlejohn/ALTextInputBar#6]
Currently using the ALTextInputBar for posting comments. But if a user is not logged in, it will present a login view controller. When I pop that view controller to go back to posting a comment, the ALTextInputBar disappears.

Tried adding the configuration to the viewWillAppear:

    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        configureInputBar()
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "keyboardFrameChanged:", name: InputAccessoryViewKeyboardFrameDidChangeNotification, object: nil)
        createRightButton() // creates the right button for the textView
        NSNotificationCenter.defaultCenter().addObserver(self,
            selector: Selector("keyboardWillShow:"),
            name: UIKeyboardWillShowNotification,
            object: nil)
        NSNotificationCenter.defaultCenter().addObserver(self,
            selector: Selector("keyboardWillHide:"),
            name: UIKeyboardWillHideNotification,
            object: nil)
    }

    func configureInputBar() {
        let leftButton = UIButton(frame: CGRectMake(0, 0, 44, 44))
        let rightButton = UIButton(frame: CGRectMake(0, 0, 44, 44))
        
        leftButton.setImage(UIImage(named: "leftIcon"), forState: UIControlState.Normal)
        rightButton.setImage(UIImage(named: "rightIcon"), forState: UIControlState.Normal)
        
        textInputBar.leftView = leftButton
        textInputBar.rightView = rightButton
        
        textInputBar.backgroundColor = UIColor.whiteColor()
    }

**Comment by Oniiichan** [comment]
Hi Alex, I'm still unable to resolve this issue. Would you mind taking a look? Thank you!

**Comment by AlexLittlejohn** [comment]
I'm not sure what is causing this for you as i can't reproduce this reliably. For starters though I would move the configuration inside `viewDidAppear` to `viewDidLoad`. Then you can try calling `reloadInputViews` inside `viewDidAppear`.
