### ISSUE TITLE
Clearing a UITabBar

### ISSUE THREAD

**Issue by wgsomerville** [AlexLittlejohn/ALTextInputBar#7]
Hey Alex,

Thanks for making this, I really like it!  I'm currently trying to use it in an app that has a UITabBar, and I am finding that it overlaps the whole bar.  Do you know of an easy way to move the text input bar so it rests just above the TabBar?

Thanks!

Walter

**Comment by AlexLittlejohn** [comment]
If you are using the intended method of layout (inputAccessoryView) then input bar is always technically attached to the top of the keyboard which would be at the bottom of the screen when it is hidden.

However you could just add it as a subview to your view controller and attach it using auto layout to the bottomLayoutGuide which should keep it above the tab bar. However you would then need to handle position changing when the keyboard is shown manually.
