### ISSUE TITLE
Unable to paste text when textview is empty

### ISSUE THREAD

**Issue by vitalyster** [AlexLittlejohn/ALTextInputBar#8]
I need to type something, or context menu will disappear

**Comment by AlexLittlejohn** [comment]
I can't reproduce this issue my self. It seems to show the paste menu correctly if i tap and hold on the textview, even when its empty.

Could you tell me how to reproduce this issue i.e. OS Version, device etc.

**Comment by vitalyster** [comment]
iOS Simulator 8.3 and 8.4, real iPhone 5S and 6 with iOS 8.3 and 8.4
![out](https://cloud.githubusercontent.com/assets/1052407/8526821/a23f7c4e-2411-11e5-949b-2cb847b51750.gif)

**Comment by AlexLittlejohn** [comment]
The paste menu item doesn't appear if there's nothing to paste. When there's nothing to select the other menu items disappear as well. Which is why it appears as though no menu is showing when there is no text.

Note: this is happening on an OS level i.e. not in the code of the component.

**Comment by vitalyster** [comment]
Well, maybe the problem with existing clipboard was when I tried to tweak insets and cursor goes under border, will try check it better.
