### ISSUE TITLE
Using method "instantiateViewControllerWithIdentifier" not showing the tool bar on the new view

### ISSUE THREAD

**Issue by Kayoto1** [AlexLittlejohn/ALTextInputBar#9]
While i create new view with instantiateViewControllerWithIdentifier the tool bar is not showing, is it possible that i did something wrong ? this happened only on ios7

Thank You

**Comment by AlexLittlejohn** [comment]
I'm not sure i understand your issue? Perhaps you could ask this on stackoverflow?
